version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kuwait-social-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
    env_file:
      - .env
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    depends_on:
      - db
      - redis
    networks:
      - kuwait-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kuwait-social-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=https://kwtsocial.com/api
    depends_on:
      - backend
    networks:
      - kuwait-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15-alpine
    container_name: kuwait-social-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=kuwait_user
      - POSTGRES_PASSWORD=secure_password
      - POSTGRES_DB=kuwait_social_ai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kuwait-network

  redis:
    image: redis:7-alpine
    container_name: kuwait-social-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - kuwait-network

volumes:
  postgres_data:
  redis_data:

networks:
  kuwait-network:
    driver: bridge
