#!/bin/bash

# Install Docker Desktop for Mac
echo "=================================================================================="
echo "🐳 Docker Desktop Installation Guide for macOS"
echo "=================================================================================="
echo ""
echo "Docker Desktop cannot be installed via command line on macOS."
echo "Please follow these steps to install Docker Desktop:"
echo ""
echo "1. Visit: https://www.docker.com/products/docker-desktop/"
echo "2. Click 'Download for Mac'"
echo "3. Choose the correct version for your Mac:"
echo "   - Apple Silicon (M1/M2/M3) or Intel chip"
echo "4. Open the downloaded Docker.dmg file"
echo "5. Drag Docker.app to Applications folder"
echo "6. Launch Docker from Applications"
echo "7. Follow the setup wizard"
echo ""
echo "After installation, verify Docker is working by running:"
echo "  docker --version"
echo "  docker-compose --version"
echo ""
echo "=================================================================================="
echo ""
echo "Alternative: Install Docker using Homebrew (if you have Homebrew installed):"
echo "  brew install --cask docker"
echo ""
echo "Note: You'll still need to launch Docker Desktop from Applications after installing."
echo "=================================================================================="