# DigitalOcean App Platform specification
name: kuwait-social-ai-frontend
region: nyc
services:
  - name: frontend
    # Option 1: Deploy from GitHub
    github:
      repo: your-github-username/your-repo-name
      branch: main
      deploy_on_push: true
    
    # Option 2: Deploy using Docker
    # dockerfile_path: Dockerfile.digitalocean
    
    # Build configuration
    build_command: npm run build
    environment_slug: node-js
    
    # Environment variables
    envs:
      - key: VITE_API_URL
        value: ${APP_URL}/api
        scope: BUILD_TIME
      - key: NODE_ENV
        value: production
        scope: BUILD_TIME
    
    # HTTP configuration
    http_port: 8080
    
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # Routes
    routes:
      - path: /
    
    # Static site configuration (alternative to Docker)
    source_dir: /
    output_dir: dist
    
# If you have a backend service, add it here:
# - name: backend
#   github:
#     repo: your-github-username/your-repo-name
#     branch: main
#     deploy_on_push: true
#   dockerfile_path: Dockerfile
#   http_port: 5000
#   routes:
#     - path: /api